attempt to compute tags

diff --git a/actions/git/list-tags/action.yaml b/actions/git/list-tags/action.yaml
--- a/actions/git/list-tags/action.yaml
+++ b/actions/git/list-tags/action.yaml
@@ -15,6 +15,6 @@ runs:
       run: |
         #!/usr/bin/env bash
         set -euo pipefail
-        tag=$(git describe --tags --abbrev=0 || echo "")
+        tag=$(git describe --tags --abbrev=0 || echo "error")
         echo "tag=${tag}" 
         echo "tag=${tag}" >> $GITHUB_OUTPUT
