update version

diff --git a/actions/tools/action.yaml b/actions/tools/action.yaml
--- a/actions/tools/action.yaml
+++ b/actions/tools/action.yaml
@@ -41,13 +41,18 @@ runs:
       run: |-
         #Debug
         maven_version="$(cat .maven)"
-        echo "MAVEN VERSION = ${maven_version}"
 
-        echo "maven-version=${maven_version}" >> $GITHUB_OUTPUT
+        if [[ $maven_version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "maven-version=${maven_version}" >> $GITHUB_OUTPUT
+        else
+          echo "Error: Maven version not allowed."
+          echo "Version = ${maven_version}"
+          exit 1
+        fi
 
     - name: Install Maven
       id: install-maven
-      if: steps.check-install.outputs.maven == 'true'
+      if: steps.check-install-tools.outputs.maven == 'true'
       uses: rhattox-shared-actions/shared-actions/actions/tools/maven@main
       with:
         maven-version: ${{ steps.get-maven-version.outputs.maven-version }}
